config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :waitlists
  resources :bookmarks
  resources :bookings
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "users/registrations"}
  resources :tours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # Custom Routes for Users
    match '/user/new', to: 'users#new', via: 'get'
    match '/user/create', to: 'users#create', via: 'post'
    match '/user/:id/edit', to: 'users#edit', via: 'get', as: 'user_edit'
    match '/user/:id', to: 'users#update', via: 'put'
    match '/user/:id', to: 'users#update', via: 'patch'
    match '/user/:id', to: 'users#destroy', via: 'delete'
  
    match '/users', to: 'users#index', via: 'get'
    match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  match '/agents', to: 'users#agent', via: 'get'
  match '/customers', to: 'users#customer', via: 'get'
  match '/tour/search' => 'tours#new_search', :via => 'get', :as => 'new_tour_search'
  match '/tour/search' => 'tours#search', :via => 'post', :as=> 'tour_search'
  root to: 'tour_app#index'

end

app/controllers/tour_app_controller.rb
class TourAppController < ApplicationController
end

app/helpers/tour_app_helper.rb
module TourAppHelper
end

app/views/tour_app/index.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>
<div class="container" style="margin-top:20px">
  <div class="jumbotron">
    <h1 class="display-4">Hello, <%= current_user.first_name%></h1>
    <p class="lead">Welcome to Tour Booking App</p>
    <hr class="my-4">
    <div class="list-group">

      <%# All %>
      <%= link_to 'View Tours', tours_path, :class => "list-group-item list-group-item-action"%>
     
     <%# Customer and Admin Features%>
     <% if current_user.is_customer || current_user.is_admin%>
        <%= link_to 'My Bookings', bookings_path, :class=>"list-group-item list-group-item-action"  %>
        <%= link_to 'My Bookmarks', bookmarks_path, :class=>"list-group-item list-group-item-action"  %>
        <%= link_to 'My Waitlists', waitlists_path, :class=>"list-group-item list-group-item-action"  %>
      <% end %>

      <%# Customer Features%>
      <% if current_user.is_customer%>
      <%= link_to 'My Reviews', reviews_path, :class=>"list-group-item list-group-item-action"  %>
      <%end%>
      <%# Agent and Admin Features%>
      <% if current_user.is_agent || current_user.is_admin %>
        <%= link_to 'Add Tour', new_tour_path, :class=>"list-group-item list-group-item-action" %>
      <% end%> 

      <%# Admin Features%>
      <% if current_user.is_admin %>
        <%= link_to 'List of Bookings', bookings_path, :method => 'get', :class => "list-group-item list-group-item-action"%>
        <%= link_to 'List of Bookmarked Users', bookmarks_path, :method => 'get', :class => "list-group-item list-group-item-action"%>
        <%= link_to 'All Reviews', reviews_path, :class=>"list-group-item list-group-item-action"  %>
        <%= link_to 'List of Waitlists', waitlists_path, :method => 'get', :class => "list-group-item list-group-item-action"%>
        <%= link_to 'View Users', users_path, :class => "list-group-item list-group-item-action"%>
        <%= link_to 'Add User', { :controller => :users, :action => :new }, :class => "list-group-item list-group-item-action"%>
        <%= link_to 'View Agents', agents_path, :class => "list-group-item list-group-item-action" %>
        <%= link_to 'View Customers', customers_path, :class => "list-group-item list-group-item-action" %> 
      <% end %>
    </div>
  </div>
</div>