config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :waitlists
  resources :bookmarks
  resources :bookings
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "users/registrations"}
  resources :tours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # Custom Routes for Users
    match '/user/new', to: 'users#new', via: 'get'
    match '/user/create', to: 'users#create', via: 'post'
    match '/user/:id/edit', to: 'users#edit', via: 'get', as: 'user_edit'
    match '/user/:id', to: 'users#update', via: 'put'
    match '/user/:id', to: 'users#update', via: 'patch'
    match '/user/:id', to: 'users#destroy', via: 'delete'
  
    match '/users', to: 'users#index', via: 'get'
    match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  match '/agents', to: 'users#agent', via: 'get'
  match '/customers', to: 'users#customer', via: 'get'
  match '/tour/search' => 'tours#new_search', :via => 'get', :as => 'new_tour_search'
  match '/tour/search' => 'tours#search', :via => 'post', :as=> 'tour_search'
  root to: 'tour_app#index'

end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :user
	belongs_to :tour

	validates_numericality_of :no_of_seats, greater_than: 0, less_than_or_equal_to: 100, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :check_prior_booking, only: [:create]

  def check_prior_booking
    @prior_booking = Booking.where(:user_id => current_user.id, :tour_id => params[:tour_id])
    unless @prior_booking.blank?
      flash[:notice] = "ERROR: Cannot reserve more than one booking for same tour"
      redirect_to root_path and return
    end
  end

  def waitlist_handler(tour_id)

      @tour = Tour.find(tour_id)
      # puts @tour.Name
      seats_available = @tour.avail_seats
      waitlists = Waitlist.where(tour_id: tour_id)

      waitlists.each do |waitlist|
        if waitlist.no_of_seats <= seats_available
          seats_available = seats_available - waitlist.no_of_seats
          @booking = Booking.new
          @booking.no_of_seats = waitlist.no_of_seats
          @booking.user_id = waitlist.user_id
          @booking.tour_id = waitlist.tour_id
          @booking.save
          @tour.avail_seats = seats_available
          @tour.avail_waitlist = @tour.avail_waitlist - waitlist.no_of_seats
          @tour.save
          ConfirmationMailer.with(bookmark: waitlist.user_id).new_confirmation_mail.deliver_now
          waitlist.destroy
        end
    end
  end

  # GET /bookings
  # GET /bookings.json
  def index
    # @booking = Booking.where(user_id: current_user.id)
    if current_user.is_admin
      @bookings = Booking.all
    elsif current_user.is_agent
      # tour_owner = Tour.where(id: params[:tour_id]).pluck(:user_id)
      @bookings = Booking.where(tour_id: params[:tour_id])#.where(user_id: tour_owner)
    elsif current_user.is_customer
      @bookings = Booking.where(user_id: current_user.id)
    end

  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @tour_id = initial_booking_params["tour_id"]
    @tour = Tour.find(@tour_id)
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create

    ## Add logic for completed trips

    booking_params[:user_id] = current_user.id
    # puts booking_params[:user_id]
    @booking = Booking.new(booking_params.except(:option))
    @tour = Tour.find(booking_params[:tour_id])
    @overbooked = false
    ready = false

    # puts @booking.no_of_seats
    # puts @tour.avail_seats
    if @booking.no_of_seats > @tour.avail_seats
      @overbooked = true
    end



    # puts booking_params
    respond_to do |format|
      if @overbooked
        if booking_params['option'] == "Book only avaialble seats"
          @booking.no_of_seats = @tour.avail_seats
          message = "We were able to book " + @booking.no_of_seats.to_s + " seats for you."
          ready = true
        elsif booking_params['option'] == "Book all avaialble seats and waitlist remaining"
          waitlist_count = @booking.no_of_seats - @tour.avail_seats
          @booking.no_of_seats = @tour.avail_seats
          waitlist = Waitlist.new({"user_id" => current_user.id, "tour_id" => booking_params[:tour_id], "no_of_seats" => waitlist_count}).save
          ready = true
          @tour.avail_waitlist = waitlist_count
          @tour.save
        elsif booking_params['option'] == "Add all seats to Waitlist"
          waitlist_count = @booking.no_of_seats
          @booking.no_of_seats = 0
          waitlist = Waitlist.new({"user_id" => current_user.id, "tour_id" => booking_params[:tour_id], "no_of_seats" => waitlist_count}).save
          ready = true
          @tour.avail_waitlist = waitlist_count
          @tour.save
        else
        end
      end

      if(@booking.no_of_seats <1)
        message = 'Unable to confirm any seats.'
      end

      if (ready or not @overbooked) and (@booking.no_of_seats <1 or @booking.save)
        @tour.avail_seats = @tour.avail_seats - @booking.no_of_seats
        @tour.save
        format.html { redirect_to @booking, notice: message }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end

  end
end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    current_seat_count = @booking.no_of_seats
    requested_seat_count = booking_params[:no_of_seats].to_i

    @tour = Tour.find(@booking.tour_id)
    
    respond_to do |format|
      if requested_seat_count > current_seat_count
        @booking.errors.add(:no_of_seats, "You can only reduce your ticket count. You have " + current_seat_count.to_s + " seats currently.")
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      elsif requested_seat_count == 0
        @booking.errors.add(:no_of_seats, "If you want to have 0 seats, please cancel the reservation.")
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      elsif @booking.update(booking_params)
            @tour.avail_seats = @tour.avail_seats - requested_seat_count + current_seat_count
            @tour.save
            waitlist_handler(@booking.tour_id)
            format.html { redirect_to @booking, notice: 'Customer booking was successfully updated to ' + requested_seat_count.to_s + " seats."}
            format.json { render :show, status: :ok, location: @booking }
      else
            format.html { render :edit }
            format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @tour = Tour.find(@booking.tour_id)
    @tour.avail_seats = @tour.avail_seats + @booking.no_of_seats
    @tour.save
    @booking.destroy
    waitlist_handler(@tour.id)
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:no_of_seats, :user_id, :tour_id, :option)
    end

    def initial_booking_params
      params.permit(:tour_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <strong>Total Seats:</strong>
  <%= Tour.find(@tour.id).total_seats %>
</p>
<p>
  <strong>Avialable Seats:</strong>
  <%= Tour.find(@tour.id).avail_seats %>
</p>
<br/>
  <div class="form-group">
    <%= form.label :no_of_seats %>
    <%= tooltip "Integral value between 1 and 100", { :tooltip => 'Booking_tooltip' }, :class => 'mytooltip' %>
    <br/>
    <%= form.number_field :no_of_seats %>
  </div>

  <div class="form-group">
  <% if @overbooked %>
    Sorry, as of this moment, there aren't enough seats to meet your request. What would you like to do?</P>
    <%= form.select :option, ["Book only avaialble seats", "Book all avaialble seats and waitlist remaining","Add all seats to Waitlist"] %>
  <% end %>
</div>

    <%= form.hidden_field :user_id, :value => current_user.id %>
    <%= form.hidden_field :tour_id, :value => @tour.id %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<!-- <h1>Editing Booking</h1> -->
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>

<%= form_with(model: @booking, local: true) do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :no_of_seats %>
    <%= form.number_field :no_of_seats %>
  </div>

  <div class="field">
  <% if @overbooked %>
    Sorry, as of this moment, there aren't enough seats to meet your request. What would you like to do?</P>
    <%= form.select :option, ["Book only avaialble seats", "Book all avaialble seats and waitlist remaining","Add all seats to Waitlist"] %>
  <% end %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>

<p id="notice"><%= notice %></p>
<h1>Booked Users / Bookings</h1>
<div class="container">
<table>
  <thead>
    <tr>
      <th>Tour</th>
      <th>User</th>
      <th>Number of Seats</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= Tour.find(booking.tour_id).Name %></td>
        <td><%= User.find(booking.user_id).first_name %></td>
        <td><%= booking.no_of_seats %></td>
        <td><%= User.find(booking.user_id).phone_number %></td>
        <td><%= User.find(booking.user_id).email %></td>
        <td><%= link_to 'Show', booking %></td>
         <% if current_user.is_admin || current_user.is_customer%>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <%end%>
        <% if current_user.is_admin || current_user.is_customer%>
        <td><%= button_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'View Tours', tours_url %>

app/views/bookings/new.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>
<!-- <h1>New Booking</h1> -->

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>

<!-- <p id="notice"><%= notice %></p> -->
<div class="container" style="margin-top:50px">
  <div class="card">
  <div class="card-body">
      <p>
        <strong> Name:</strong>
        <%=  User.find(@booking.user_id).first_name  %>
        <%=  User.find(@booking.user_id).last_name %>
      </p>

      <p> <strong> Phone Number: </strong>
        <%=  User.find(@booking.user_id).phone_number %>
      </p>
      
      <p>
        <strong> Email:</strong>
        <%=  User.find(@booking.user_id).email %>
      </p>

      <p>
        <strong> Tour Booked:</strong>
        <%=  Tour.find(@booking.tour_id).Name %>
      </p>
    <p>
      <strong>Number of Seats:</strong>
      <%= @booking.no_of_seats %>
    </p>


<p>
  <strong>Price:</strong>
  <%= Tour.find(@booking.tour_id).Price %>
</p>

<div class="actions">
    <% if current_user.is_admin || ( current_user.is_customer ) %>
       <%= link_to 'Edit', edit_booking_path(@booking) ,:class=>"btn btn-success"%>
    <% end %>
 </div>
<div class="actions">
    <%tour_status = Tour.find(@booking.tour_id).status %>
    <% if (current_user.is_admin || current_user.is_customer) && (tour_status.eql?"Completed")  %>
       <%= link_to 'Add Review', new_review_path(:booking_id => @booking),:class=>"btn btn-success"%>
    <% end %>
 </div>
<%= link_to 'Back', bookings_path , :class=>"btn btn-secondary float-right"%>
 </div>
</div>
</div>