config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :waitlists
  resources :bookmarks
  resources :bookings
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "users/registrations"}
  resources :tours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # Custom Routes for Users
    match '/user/new', to: 'users#new', via: 'get'
    match '/user/create', to: 'users#create', via: 'post'
    match '/user/:id/edit', to: 'users#edit', via: 'get', as: 'user_edit'
    match '/user/:id', to: 'users#update', via: 'put'
    match '/user/:id', to: 'users#update', via: 'patch'
    match '/user/:id', to: 'users#destroy', via: 'delete'
  
    match '/users', to: 'users#index', via: 'get'
    match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  match '/agents', to: 'users#agent', via: 'get'
  match '/customers', to: 'users#customer', via: 'get'
  match '/tour/search' => 'tours#new_search', :via => 'get', :as => 'new_tour_search'
  match '/tour/search' => 'tours#search', :via => 'post', :as=> 'tour_search'
  root to: 'tour_app#index'

end

app/models/tour.rb
class Tour < ApplicationRecord
	belongs_to :user, optional: true 
	before_create :set_available_seats
	
	has_many :bookings
	has_many :bookmark
	mount_uploader :image, ImageUploader
	serialize :image, JSON
	validate :image_size_validation
	

	validates_presence_of :Name, :pickup, :status, :countries, :states, :Description
	validates_numericality_of :total_seats, greater_than: 0, less_than_or_equal_to: 100, presence: true #avail_seats
	validates_numericality_of  :Price, greater_than: 0, less_than_or_equal_to: 300000
	validates :start_date, presence: true
	validates :end_date, presence: true
	validates :booking_deadline, presence: true
	validate :valid_end_date?


  def valid_end_date?
	  errors.add(:start_date, "must be before end_date") unless start_date < end_date
	end

# Image validation in image_uloader.rb
	def image_size_validation
		errors[:image] << "should be less than 5MB" if image.size > 5.megabytes
	end

	private

	def set_available_seats
	  self.avail_seats = self.total_seats
	end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only:[:search, :new_search]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)
    @tour.avail_seats = @tour.total_seats
    @tour.user_id = current_user.id
    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    if params[:tour][:remove_image].present?
      @tour.remove_image!
    end
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  INTEGER_MAX = 300000
  PRICE_MAPPING = {
    1 => [0, 1999],
    2 => [2000, 4999],
    3 => [5000, 9999],
    4 => [10000, 14999],
    5 => [15000, INTEGER_MAX]
  }

  def new_search
  end

  def search 
    @sp = params.fetch(:search_params, {})
    @tours = Tour.all
    @tours = @tours.where('start_date >= ?', "%#{@sp['StartDate']}%")if @sp['StartDate'].present?
    @tours = @tours.where('end_date >= ?', "#{@sp['EndDate']}") if @sp['EndDate'].present?
    @tours = @tours.where(['Name LIKE ?', "%#{@sp['Name']}%"]) if @sp['Name'].present? && @sp['Name'] != ""
    @tours = @tours.where(['countries LIKE ?', "%#{@sp['countries']}%"]) if @sp['countries'].present? && @sp['countries'] != ""
    @tours = @tours.where(:Price => PRICE_MAPPING[@sp['Price'].to_i][0]...PRICE_MAPPING[@sp['Price'].to_i][1]) if @sp['Price'].present?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:Name, :Description, :Price, :start_date, :end_date, :pickup, :total_seats, :avail_seats, :avail_waitlist, :status, :booking_deadline, :countries, :states, :user_id, :image)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
    def tooltip(content, options = {}, html_options = {}, *parameters_for_method_reference)
        html_options[:title] = options[:tooltip]
        html_options[:class] = html_options[:class] || 'tooltip'
        content_tag("span", content, html_options)
        end
    def price_options
        [["0-1999", 1], ["2000-4999", 2], ["5000-9999", 3], ["10000-14999", 4], ["15000+", 5]]
    end
end

app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true, :html => {multipart: true}) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Name %>
    <%= form.text_field :Name , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :Description %>
    <%= tooltip "Please Don't Overwhelm Customer, Keep it Nice and Short.(<=200)", { :tooltip => 'Tour_tooltip' }, :class => 'mytooltip' %>
    <%= form.text_area :Description, :maxlength => 200, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Price %>
    <%= tooltip "Integral value between 0 and 300000", { :tooltip => 'Tour_tooltip' }, :class => 'mytooltip' %>
    <%= form.text_field :Price, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, min: Date.today , :class => "form-control"%>
  </div>

   <div class="form-group">
    <%= form.label :end_date %>
    <%= tooltip "End Date should be after Start Date", { :tooltip => 'Tour_tooltip' }, :class => 'mytooltip' %>
    <%= form.date_field :end_date, min: Date.tomorrow , :class => "form-control" %>
  </div>

   <div class="form-group">
    <%= form.label "Start location" %>
    <%= form.text_field :pickup , :class => "form-control"%>
  </div>

   <div class="form-group">
    <%= form.label :total_seats %>
    <%= tooltip "Integral value between 1 and 100", { :tooltip => 'Tour_tooltip' }, :class => 'mytooltip' %>
    <%= form.text_field :total_seats, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.radio_button :status, 'Active' %> Active<br />
    <%= form.radio_button :status, 'Completed' %> Completed<br />
  </div>

  <div class="form-group">
    <%= form.label :booking_deadline %>
    <%= form.date_field :booking_deadline, :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :countries %>
    <%= tooltip "Seperate the countries by a comma", { :tooltip => 'Tour_tooltip' }, :class => 'mytooltip' %>
    <%= form.text_field :countries , :class => "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :states %>
    <%= tooltip "Separate the states by a comma", { :tooltip => 'Tour_tooltip' }, :class => 'mytooltip' %>
    <%= form.text_field :states, :class => "form-control" %>
  </div>

  <div>
    <%= form.label :image %>
    <%= tooltip "Allowed Tyes: JPG, JPEG, PNG, Max 5 MB", { :tooltip => 'Tour_tooltip' }, :class => 'mytooltip' %>
    <%= form.file_field :image ,data: { max_file_size: 5.megabytes }%>
  </div>

<p>
    <label>
      <%= form.check_box :remove_image %>
      Remove Image
    </label>
  </p>
  <div class="actions">
    <div class="form-group">
      <%= form.submit :class=> "btn btn-success" %>
      <%# <%= link_to 'Back', tours_path, :class=>"btn btn-secondary" %> 
    </div>
  </div>
<% end %>

app/views/tours/_table.html.erb
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Totals Seats</th>
        <th>Available Seats</th>
        <th>Waitlist</th>
        <th>Status</th>
        <th>Deadline</th>
        <th>Countries</th>
        <th>States</th>

        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @tours.each do |tour| %>
        <tr>
          <td><%= tour.Name %></td>
          <td><%= tour.Description %></td>
          <td><%= tour.Price %></td>
          <td><%= tour.start_date %></td>
          <td><%= tour.end_date %></td>
          <td><%= tour.total_seats %></td>
          <td><%= tour.avail_seats %></td>
          <td><%= tour.avail_waitlist %></td>
          <td><%= tour.status %></td>
          <td><%= tour.booking_deadline %></td>
          <td><%= tour.countries %></td>
          <td><%= tour.states %></td>
          <td><%= link_to 'Show', tour %></td>
          <%# <% if current_user.is_admin || ( current_user.is_agent && current_user == tour.user_id ) %> 
              <%# <td><%= link_to 'Edit', edit_tour_path(tour) %>
          <%# <%end %> 
          <%# <% if current_user.is_admin || ( current_user.is_agent && current_user == tour ) %>   
              <%# <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } </td>%>
          <%# <% end %> 
          
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/tours/edit.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>

<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path, :class => "btn btn-secondary float-right"%>

app/views/tours/index.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Tours</h1>

   <p>
   <%= link_to 'Search Tours', new_tour_search_path , :class => "btn btn-success"%>
   </p>
<%= render 'table' %>

  <br>	
<% if current_user.is_admin || current_user.is_agent%>
  <%= link_to 'New Tour', new_tour_path , :class => "btn btn-success"%>
  <%end%>
 </div> 

app/views/tours/new.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>

<h1>New Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path, :class=>"btn btn-secondary float-right"%>

app/views/tours/new_search.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>

<%= form_for :search_params, url:"search" do |form| %>

  <div class="field">
    <%= form.label 'Name' %><br />
    <%= form.text_field :Name, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label 'Countries' %><br />
    <%= form.text_field :countries, autofocus: true %>
  </div>
  <div class="field">
    <%= form.label 'Tour Price' %><br />
    <%= form.select :Price, price_options, :include_blank => true %>
  </div>
  <div class="field">
    <%= form.label 'Start Date' %><br />
    <%= form.date_field :StartDate, min: Date.today, :include_blank => true %>
  </div>
  <%# <div class="field">
    <%= form.label 'End Date' <br />%>
    <%# <%= form.date_field :EndDate, min: Date.tomorrow, :include_blank => true %>
  <%# </div> %>
  <div class="actions">
    <%= form.submit "Search" %>
  </div>
<% end %>

<%= link_to 'Back', tours_path, :class=>"btn btn-secondary"%>

app/views/tours/search.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>

<div class="container">
  <h1>Matching Tours</h1>
   <p>
    <%= link_to 'Search Tours', new_tour_search_path %>
  </p>
    <%= render 'table' %>
<%= link_to 'Back', tours_path,:class=>"btn btn-secondary float-right" %>
 <% if current_user.is_admin || current_user.is_agent%>
  <%= link_to 'New Tour', new_tour_path , :class => "btn btn-success"%>
  <%end%>
</div>

app/views/tours/show.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>
<div class="container" style="margin-top:50px">
  <div class="card">
  <div class="card-body">
    <h3 class="card-title">
        <%= @tour.Name %>
    </h3>

    <p>
      <strong>Description:</strong>
      <%= @tour.Description %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @tour.Price %>
    </p>

    <p>
      <strong>Start Date:</strong>
      <%= @tour.start_date %>
    </p>

    <p>
      <strong>End Date:</strong>
      <%= @tour.end_date %>
    </p>

    <p>
      <strong>Total Seats:</strong>
      <%= @tour.total_seats %>
    </p>

    <p>
      <strong>Available Seats:</strong>
      <%= @tour.avail_seats %>
    </p>

    <p>
      <strong>Waitlist Number:</strong>
      <%= @tour.avail_waitlist %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @tour.status %>
    </p>

    <p>
      <strong>Booking Deadline:</strong>
      <%= @tour.booking_deadline %>
    </p>

    <p>
      <strong>Countries:</strong>
      <%= @tour.countries %>
    </p>

    <p>
      <strong>States:</strong>
      <%= @tour.states %>
    </p>

     <p>
      <strong>Contact Information</strong>
    </p>

    <p>
      <strong>Name:</strong>
      <%= User.find(@tour.user_id).first_name %>
    </p>

    <p>
      <strong>Email Id:</strong>
      <%= User.find(@tour.user_id).email %>
    </p>

    <p>
      <strong>Contact No.:</strong>
      <%= User.find(@tour.user_id).phone_number %>
    </p>

    <%= image_tag(@tour.image.url, alt: 'Image') if @tour.image? %>
    <br/><br/>
    
    <div class="actions">
    <% if (current_user.is_admin ||  current_user.is_customer ) && (@tour.status.eql?"Active")%>
       <%= link_to 'Book this tour!', new_booking_path(:tour_id => @tour) ,:class=>"btn btn-success"%>
    <% end %>
    </div>

    <div class="actions">
    <% if current_user.is_admin || ( current_user.is_customer ) %>
      <%= button_to 'Interested', bookmarks_path(tour_id: @tour.id), :method => 'post', :class=>"btn btn-success" %>
    <% end %>
  </div>

    <div class="actions">
    <% if current_user.is_admin || ( current_user.is_agent && current_user.id == @tour.user_id) %>
        <%= link_to 'List of Bookmarked Users', bookmarks_path(tour_id: @tour.id), :method => 'get', :class=>"btn btn-success" %>
    <% end %>
    </div>

    <div class="actions">
    <% if current_user.is_admin || ( current_user.is_agent && current_user.id == @tour.user_id) %>
        <%= link_to 'List of Booked Users', bookings_path(tour_id: @tour.id), :method => 'get', :class=>"btn btn-success" %>
    <% end %>
    </div>

    <div class="actions">
    <% if current_user.is_admin || ( current_user.is_agent && current_user.id == @tour.user_id) %>
        <%= link_to 'Edit', edit_tour_path(@tour), :class=>"btn btn-success"%>
    <% end %>
    </div>

    <br/>
    <% if current_user.is_admin || ( current_user.is_agent && current_user.id == @tour.user_id) %>
        <%= button_to 'Destroy', @tour, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-outline-danger"%>
    <% end %>
    <%= link_to 'Back', tours_path, :class=>"btn btn-secondary float-right" %>
  </div>

  <%# <%= render "partials/reviews", reviews: Review.find(@tour.id) %>

<h4> Reviews</h4>
<% Review.where(tour_id: @tour.id).each do |review| %>

<div class="container", style="margin-top:10px">
  <div class="card">
    <div class="card-header">
      <p style="display:inline"><strong><%= User.find(review.user_id).first_name %> </strong></p>
      <p class="float-right" style="display:inline;"> <%= review.created_at %> </p>
    </div>
    <div class="card-body">
      <p> <%= review.subject %> </p>
      <p> <%= review.content %> </p>
    </div>
  </div>
</div>
<% end %>
</div>